### ISSUE TITLE
No events captured when compiled in `--release` (`production` environment)

### ISSUE THREAD

**Issue by Niedzwiedzw** [getsentry/sentry-rust#502]
### Environment

What version are you running? Etc.
```toml
sentry = { version = "0.27.0", features = ["backtrace", "contexts", "httpdate",  "panic", "reqwest", "reqwest_", "rustls", "sentry-backtrace", "sentry-contexts", "sentry-panic", "sentry-tracing", "tokio", "transport",], default-features=false }
sentry-tracing = "0.27.0"
tracing = "0.1"
```

### Steps to Reproduce
```bash
cd /tmp/
git clone https://github.com/Grupa-Pieprzyk/pieprzyk-logging
export TEST_SENTRY_URL=XXX
cargo test
cargo test --release
```

### Expected Result

In my sentry dashboard I'd expect to see errors (events in general actually)  that occured in `production` environment

### Actual Result
I only see events for `development` environment (compiled without `--release` flag)
