### ISSUE TITLE
Sentry Tracing not working for me

### ISSUE THREAD

**Issue by Hugo-Persson** [getsentry/sentry-rust#567]
I don't know if I missunderstand the documentation for sentry tracing integration but I can not get event capturing to work. This my test code:
```rust
#[tokio::main]
#[tracing::instrument]
async fn main() -> Result<(), Box<dyn Error>> {
    dotenv().ok();
    let _guard = sentry::init((
        "https://...",
        sentry::ClientOptions {
            release: sentry::release_name!(),
            sample_rate: 1.0,
            attach_stacktrace: true,
            ..Default::default()
        },
    ));

    let tracing_layer =
        tracing_subscriber::fmt::layer().with_filter(filter::filter_fn(|metadata| {
            vec![Level::INFO, Level::ERROR, Level::WARN].contains(metadata.level())
        }));
    let sentry_layer = sentry_tracing::layer();
    let _ = tracing_subscriber::registry()
        .with(tracing_layer)
        .with(sentry_layer)
        .init();

    test_sentry();
    const VERSION: &str = env!("CARGO_PKG_VERSION");
    info!("Starting application with version {}", VERSION);
    panic!("A panic");
    Ok(())
}

#[tracing::instrument]
fn test_sentry() {
    error!("Testing");
}
```
This is my `cargo.toml` dependencies
```toml
[dependencies]
reqwest = { version = "0.11.13", features = ["multipart", "json"] }
tokio = { version = "1.2", features = ["full"] }
serde_json = "1.0"
serde = "1.0"
lapin = "2.1.1"
futures-lite = "1.12.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-test = "0.1"
dotenv = "0.15.0"
base64 = "0.13.1"
async-trait = "0.1.64"
web-push = "0.9.3"
sentry = {version = "0.23.0", default-features = false, features = ["backtrace", "log", "contexts", "panic", "transport", "reqwest", "rustls", "tracing"]}
lettre = "0.10.2"
regex = "1.5"
sentry-tracing = "0.30.0"
```

The panic event is recieved in Sentry but not the "Testing" error. Do anyone know what I am doing wrong?
